version: '3.8'
services:
  react-app:
    image: vite-docker-container
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"
